version: '3.3'image.png
networks:
  gitlab:
    external:
      name: link_utama
services:
  web:
    image: gitlab/gitlab-ce:13.5.0-ce.0
    restart: always
    container_name: gitlab
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://{IP_Address}'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - '80:80'
      - '433:443'
      - '22:22'
      - '5050:5050'
      - '5015:5015'
    networks:
      - gitlab
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
  
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    networks:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
    restart: unless-stopped